### ISSUE TITLE
`ramda` better as a peer dependency

### ISSUE THREAD

**Issue by mAAdhaTTah** [megawac/babel-plugin-ramda#17]
Right now, when I install, the babel plugin & ramda, I get two versions installed. It appears the babel plugin does correctly resolves to the top-level version (rather than the old-ish version it installs itself) but it seems unnecessarily duplicative to install both versions of `ramda`. Moving to a peer dependency would fix this.

**Comment by megawac** [comment]
Can you create a PR for this -- I definetely wouldnt object!
