### ISSUE TITLE
Throws error for every `export *` statement

### ISSUE THREAD

**Issue by jeffmomo** [megawac/babel-plugin-ramda#26]
We're not checking if the import source is from `ramda`
[here](https://github.com/megawac/babel-plugin-ramda/commit/3741e614935deac0e6d962c4a717c3ffb10cd02c#diff-1fdf421c05c1140f6d71444ea2b27638R75) 
So it throws the error on every single `export *` statement

**Comment by megawac** [comment]
oh shoot! my bad

**Comment by megawac** [comment]
Fixed in 1.4.2

**Comment by Koleok** [comment]
As of merging #27 all my jest tests for files that import ramda like 
```js
import R from 'ramda';
```
are failing with the following

```bash
FAIL  my-file.spec.js
  ● Test suite failed to run

    /path-to-project/my-file.js: `export * from "ramda"` defeats the purpose of babel-plugin-ramda
```

**Comment by Koleok** [comment]
Does this mean in order to continue using this handy plugin am I now facing the requirement of switching to
```js
import { add } from 'ramda';
```

for every ramda import?

**Comment by megawac** [comment]
No, that shouldn't be happening

**Comment by megawac** [comment]
I think I'm just going to revert that warning

**Comment by megawac** [comment]
@Koleok can you try again with 1.4.3?

**Comment by Koleok** [comment]
@megawac forgot to check back, works now with `1.4.3` 🎉

**Comment by megawac** [comment]
Cool thanks! I just forgot to rebuild the distributables then
