### ISSUE TITLE
ramda/src vs ramda/es

### ISSUE THREAD

**Issue by JacobBlomgren** [megawac/babel-plugin-ramda#31]
With the release of ramda v25, would it be possible to use `ramda/es` instead of `ramda/src`? As I understand it, this plugin might very well be the solution to the tree shaking problems that I and many others have with ramda, as discussed in ramda/ramda#2355 and ramda/ramda#1505, but that seems to necessitate the use of `ramda/es`. If so, I could help with a PR.

**Comment by JacobBlomgren** [comment]
Ok, so it turns out that this plugin works as it is, the problem for me was elsewhere in my webpack configuration. That being said, using `es` over `src` still seems preferable, as ES modules are the future and the direction that Ramda has taken. As a thank you for a great plugin, I could still help with a PR if you want... But I suppose that requires either a `useES` option, or checking if the `es` folder exists with `fs.existsSync` and then defaulting to that. The latter is neat, but would be harder to test, I suppose.

**Comment by megawac** [comment]
Sorry, haven't looked at my issue tracker in a while. I would support a `useES` option hands down, I wouldn't want to default to `es` at the moment as that might require users to modify their configurations as `es` doesn't always work by default unless this has changed. I recall having to configure babel to parse some node_modules that exported untranspiled code
