### ISSUE TITLE
useES config not work in 1.5.0

### ISSUE THREAD

**Issue by little-yao** [megawac/babel-plugin-ramda#38]
I want to use ['ramda', { 'useES': true }] so that turn 'ramda/src/**' to 'ramda/es/**', but it does not work.
when I saw the source code, I find the release of 1.5.0 is the same as 1.4.3.
here is my modules info
![image](https://user-images.githubusercontent.com/37481369/37557856-c5539fac-2a45-11e8-8b2a-7fe4f916ccd8.png)
![image](https://user-images.githubusercontent.com/37481369/37557989-e6b43ea2-2a47-11e8-8c53-a1875e3569f7.png)

**Comment by JacobBlomgren** [comment]
Same for me... @megawac

**Comment by megawac** [comment]
That's strange as the [v1.5.0 tag for modules.js](https://github.com/megawac/babel-plugin-ramda/blob/v1.5.0/src/modules.js#L30) looks like it should correctly resolve the `/es` folder.

I just published `v1.6.1` if you have a chance can you try to reproduce in `v1.6.1` as it appears fixed based on my testing.

**Comment by JacobBlomgren** [comment]
It sure works now! But strange, I agree.
