### ISSUE TITLE
1.6.1: Strange NodePath error, not present with 1.6.0

### ISSUE THREAD

**Issue by iest** [megawac/babel-plugin-ramda#41]
Firstly, thanks for creating this plugin! I've found it incredibly useful.

However when adding `v1.6.1` to a project recently, we got this strange error when running babel:
`NodePath has been removed so is read-only. (This is an error on an internal node. Probably an internal error)`.

However, `v1.6.0` does not have the issue. I'm guessing the `package-lock.json` added alongside `v1.6.1` locked down a dodgy babel dependancy?

Might be worth regenerating a fresh package lock?

**Comment by megawac** [comment]
Thanks for looking into this @sandfox. Yep, I mispublished 1.5.0 and 1.6.0 which was corrected in 1.6.1 (I forgot to run `npm run build` before publishing :/). This is likely a result of #37 which added Babel 7 support and added the `helper-module-imports` dependency. Is there a repo I can reproduce this against as running babel with the test cases on master seem to work.

**Comment by megawac** [comment]
@phyllisstein have you encountered this error before perhaps? I seem to recall it occurring in a travis build when babel 7 compatibility was initially proposed.

**Comment by phyllisstein** [comment]
I'm a little embarrassed to admit that this _has_ come up once or twice, and I just haven't had the time to dig deep enough to figure out a fix or file a ticket. _Mea culpa_---forgive the laziness.

In all the cases I've seen it in my projects, the culprit has been an unused Ramda import. I would suggest a quick audit for cases where you `import R from 'ramda'` and then don't invoke `R`.

That said, that's definitely not a satisfactory answer. I'll spend some time this weekend trying to figure out what might be going on.

**Comment by mAAdhaTTah** [comment]
I just got this error, and I think I know what the issue is (in my case): it's a conflict with the module to commonjs transform, which also removes the import statement to replace it w/ a require statement. So when babel-plugin-ramda goes to remove it, it's already gone.
