### ISSUE TITLE
Using a changelog / release notes to help developers to upgrade version of babel plugin ramda

### ISSUE THREAD

**Issue by trollepierre** [megawac/babel-plugin-ramda#44]

**Comment by lensbart** [comment]
Agree — the recent update from 1.6.3 to 2.0.0 seems to have been a version number upgrade only, which is a bit confusing

**Comment by megawac** [comment]
It changed the version of babel we support which may of not been fully compatible with older versions of babel. That's why we tagged it as a major bump.

**Comment by megawac** [comment]
Thanks @lensbart! I didn't see that MR until now, sorry for the delay been really busy with work and not checking my projects.
