### ISSUE TITLE
Update Babel 7

### ISSUE THREAD

**Issue by trollepierre** [megawac/babel-plugin-ramda#45]

**Comment by mbfisher** [comment]
Hey! Do you know when you'll release support for Babel 7?

**Comment by L2D22** [comment]
@mbfisher a PR for babel 7 went through, we just need to update npm.  I'm not sure what the process for testing is or the ETA, hoping it's soon though.

**Comment by cihati** [comment]
@L2D22 any news on this?

**Comment by trollepierre** [comment]
It looks like it's done.

**Comment by trollepierre** [comment]
This commit shows that this issue is solved:
https://github.com/megawac/babel-plugin-ramda/commit/5389950fec8ee23a51fb82142f0f6b2f18d28abd

**Comment by IanVS** [comment]
Hmmm, unfortunately even though it's in master, it's not yet released to npm: https://github.com/megawac/babel-plugin-ramda/compare/v1.6.3...master

**Comment by megawac** [comment]
Sure, sorry for the delay

**Comment by megawac** [comment]
Published in https://github.com/megawac/babel-plugin-ramda/releases/tag/v2.0.0
