### ISSUE TITLE
Is there any specific functionality compared to Babel import plugin?

### ISSUE THREAD

**Issue by malyzeli** [megawac/babel-plugin-ramda#52]
I found that using [`babel-plugin-import`](https://github.com/ant-design/babel-plugin-import) to enable tree shaking is recommended by various other utility libraries (Lodash, Material UI, Ant Design).

If I understand correctly, it solves exactly the same problem as this project. Is there any reason to use this library specifically (anything that it is doing better) or I will achieve same results with babel import plugin?

**Comment by megawac** [comment]
This library will do a better job than import if all you're using is `babel` to transpile files, which you probably aren't. Otherwise if you're using webpack, rollup, or any other bundler that supports tree shaking you can compare your results to see which works better, they likely will be similar.
