### ISSUE TITLE
Add tag to support Ramda v0.28.0

### ISSUE THREAD

**Issue by loveboat** [megawac/babel-plugin-ramda#62]
As `merge` has been deprecated in v0.28.0 of Ramda we can't upgrade our Ramda version due to a dependency on this package.

I see support for this change has already been committed [here](https://github.com/megawac/babel-plugin-ramda/commit/c6f56fa64aa17a4eda88ec76f5006d56ee3f9818) - replacing `merge` with `mergeRight`.

Can you tag a release with this commit in so we can upgrade please?

**Comment by pultik** [comment]
@megawac When will the new version be released?

**Comment by megawac** [comment]
This should be working in the current (2.1.1) version
