### ISSUE TITLE
Missing lib folder in v2.1.0

### ISSUE THREAD

**Issue by RobinCsl** [megawac/babel-plugin-ramda#64]
Hello 👋 

It seems the `lib/` folder is missing in the published NPM package for version 2.1.0, published 2 days ago.

Compare v2.0.0 ([source](https://unpkg.com/browse/babel-plugin-ramda@2.0.0/)):
![Screenshot 2022-06-16 at 15 58 12](https://user-images.githubusercontent.com/22741774/174086627-90d833ae-607d-4e17-9ebb-7f68ac3f5abd.png)

and v2.1.0 ([source](https://unpkg.com/browse/babel-plugin-ramda@2.1.0/)):
![Screenshot 2022-06-16 at 15 56 17](https://user-images.githubusercontent.com/22741774/174086709-55c606ba-0ea9-4770-b283-70ebb41e5db5.png)

Could you please publish a new version with the missing files?

Many thanks

**Comment by RobinCsl** [comment]
@megawac is there any way I can help you to fix this?

**Comment by megawac** [comment]
Sorry I'll take a look this evening

**Comment by megawac** [comment]
Should be fixed in 2.1.1

![image](https://user-images.githubusercontent.com/3475472/175119848-c9e23958-0e02-4690-b9dd-61801232892b.png)

**Comment by RobinCsl** [comment]
Great, thank you very much!
